version: '3.7'
services:
    kafka-server:
        image: apache/kafka:latest   #utilizzo immagine ufficiale di kafka, ha bisogno di tutte quelle variabili d'ambiente
        hostname: broker
        container_name: broker
        ports:
            - '9092:9092'
        environment:
            KAFKA_NODE_ID: 1
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
            KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://broker:9092,PLAINTEXT://broker:19092'
            KAFKA_PROCESS_ROLES: 'broker,controller'
            KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
            KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
            KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
            KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
            CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
        networks: 
              tap:
                 ipv4_address: 10.0.100.24
    kart-topics:
        image: apache/kafka:latest    #creo nuobo container solo per utilizzare l'eseguibile per creare un topic
        command: > 
               bash -c "
               /opt/kafka/bin/kafka-topics.sh --create --topic topicCountries --bootstrap-server broker:9092"
        depends_on:
             - kafka-server
    logstash: 
        image: docker.elastic.co/logstash/logstash:8.13.0
        container_name: Logstash
        environment:
                XPACK_MONITORING_ENABLED: "false"
       #ports:
            #- 8081:8080
        networks: 
                tap:
                   ipv4_address: 10.0.100.22
        volumes:
               - ./docker_logstash/pipeline/log.conf:/usr/share/logstash/pipeline/logstash.conf
    telegram_bot:
           image: telegram_bot:latest
           #environment:
             #TOKEN: 
           networks: 
              tap:
                 ipv4_address: 10.0.100.23
networks:
    tap:
        name: tap
        driver: bridge
        ipam: 
            config:
                 - subnet: 10.0.100.1/24
        external: true

